Order/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
	#   /order/  urls
	#url for adding an order, web form, after choosing the menu
    url(r'^new/(?P<pk>[0-9]+)/$', views.get_order, name='get_order'),
    #url to the form where you see the orders associated with a menu
    url(r'^(?P<pk>[0-9]+)/$', views.updateStatus, name='order_sent'),
    #url to the form where the order status is checked
    url(r'^check_code/$', views.get_code, name='check_code'),
    #url  for the page where is displayed the order details.
    url(r'^check_status/$', views.checkCode, name='check_status'),
]

api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #   /api/  urls
    #url for sending all the menus for today.
    url(r'^menus/$', views.MenuList.as_view()),
    #url for operations with a menu like update,delete 
    url(r'^menus/(?P<pk>[0-9]+)/$', views.MenuDetail.as_view()),
    #url to see all the orders(GET)/ to add a new order (POST)
    url(r'^orders/$', views.OrderList.as_view()),
    #url to check the details of an order
    url(r'^code/$', views.orderByCode.as_view()),
    #url to set the rating to an update
    url(r'^rating/$', views.updateRating.as_view()),
]	

restaurant/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import Meniu

urlpatterns = [
	url(r'^meniu/', include('Meniu.urls', namespace="meniu")),
	url(r'^order/', include('Order.urls', namespace="order")),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', Meniu.views.get_name),
]

Order/models.py
from __future__ import unicode_literals
from django.core.validators import RegexValidator
from django.db import models
from Meniu.models import Menu


#the possible status o an order.
STATUS_CHOICES = (
    (0, "Pending"),
    (1, "Sent"),
    (2, "Finalized")
)
# Orde model
class Order(models.Model):
    name = models.CharField(max_length = 200)
    email = models.EmailField()
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone = models.CharField(validators=[phone_regex],max_length = 15)
    adress = models.CharField(max_length = 200)
    id_menu = models.ForeignKey(Menu)
    rating = models.FloatField(default=0)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)

    def __unicode__(self):
        return self.name

Order/forms.py
from django import forms
from restaurant.utils import validateString
from Order.models import Order
from Meniu.models import Menu
from django.forms import ModelForm
import datetime 


#class for the add order form
class newOrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'email', 'phone', 'adress', 'id_menu']

    def __init__(self, *args, **kwargs):
        id_menu = kwargs.pop('id_menu', None)
        today = datetime.date.today()
        super(newOrderForm, self).__init__(*args, **kwargs)
        self.fields['id_menu'].initial = id_menu
        self.fields['id_menu'].widget = forms.HiddenInput()

    #functions which ensure  that the input data is si valid, for the order form  
    def clean_name(self):
        name = self.cleaned_data.get('name')
        if validateString(name) == True:
            return name
        raise forms.ValidationError("invalid date")
        
    def clean_adress(self):
        adress = self.cleaned_data.get('adress')
        if validateString(adress) == True:
            return adress
        raise forms.ValidationError("invalid date")

#class for the check code form
class codeForm(forms.Form):
    # TODO: Define form fields here
    code = forms.CharField(label='code', max_length=100)
#functions which ensure  that the input data - code is valid
    def clean_code(self):
        #import ipdb; ipdb.set_trace()
        code = self.cleaned_data.get('code')
        if validateString(code) == False:
            raise forms.ValidationError("invalid date")
        cod = code.split("-")
        if len(cod) != 2:
            raise forms.ValidationError("invalid date")
        try:
            int(cod[0])
            int(cod[1])
        except:
            raise forms.ValidationError("invalid date")
        return code

    

Order/views.py
from django.shortcuts import render,redirect
from django.template import loader
from Order.models import Order
from Meniu.models import Menu
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from .forms import *
from django.contrib import messages
from django.core.mail import send_mail
from restaurant.utils import *

#views for order
#method used to get an order
def get_order(request, pk):
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = newOrderForm(request.POST, id_menu=pk)
        if form.is_valid():
            form.save()
            #create the details of email
            subject = "Order confirmation Restaurant Archers"
            mail = form.data["email"]
            menu_code = str(form.data["id_menu"]) + "-"
            orderr = Order.objects.last()
            menu_code += str(orderr.pk)
            send_mail(subject, menu_code, "restaurantarchers@gmail.com", [mail])
            messages.success(request, 'Element added.')
            #redirect to the list of menus
            return redirect('meniu:view-daily')
        else:
            messages.error(request, 'Data is invalid.')
    # create a form
    else:
        form = newOrderForm(id_menu=pk)

    return render(request, 'Order/newOrder.html', {'form': form})

#method used to get an order
def updateStatus(request,pk):
    selectedOrder = Order.objects.get(id=pk)
    selectedOrder.status = 1
    idMeniu = selectedOrder.id_menu.pk
    meniu = Menu.objects.get(pk=idMeniu)
    selectedOrder.save()
    orders = Order.objects.filter(id_menu__pk=idMeniu)
    return render(request, 'Meniu/ordersByMenu.html', {'n':meniu ,'orders': orders})

#method used to get a code and if it is valid, it returns the details of the order
def get_code(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = codeForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            code = form.data['code']
            tup = validateCode(code)
            meniu = Menu.objects.get(pk=tup[0])
            comanda = Order.objects.get(pk=tup[1])
            return render(request, 'Order/orderStatus.html', {'m':meniu ,'c': comanda})

    else:
        form = codeForm()
    return render(request, 'Order/verifyCode.html', {'form': form})
    
#returns tje details of the order
def checkCode(request):
    import ipdb; ipdb.set_trace()
    data = request.POST
    try:
        receivedData = data["code"]
    except:
        pass
    tup = validateCode(receivedData)
    meniu = Menu.objects.get(pk=tup[0])
    comanda = Order.objects.get(pk=tup[1])
    return render(request, 'Order/orderStatus.html', {'m':meniu ,'c': comanda})

restaurant/templates/Order/newOrder.html
{% extends 'base.html' %}

{% block content %}


  <div class="content--menu">
    <main class="page-content">
      <section class="page page-register gradient--addmenu">
        <div class="content">

          <article class="card registration__card">
            <form class="form" action="" method="post" id="contact">
              {% csrf_token %}
              <div class="form__group">

                <label for ="id_name" class="form__label form__component"> Name </label>
                <input type="text"  id="id_name" maxlength="200" name="name"  class="form__input form__component js-form-input "  minlength="3"   required pattern="[A-Za-z]+" /> 
                <span class="error">This field is required</span>
              </div><!-- /form group -->
    
              <div class="form__group">

                <label for="id_email" class="form__label form__component">Email</label>
                <input type="email" id="id_email" maxlength="254" name="email" class="form__input form__component js-form-input" required pattern ="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"  />
                <span class="error">A valid email address is required</span>        
              </div><!-- /form group -->
    
              <div class="form__group">
            
                {{ form.id_menu }}

              </div>

              <div for="id_phone" class="form__group">
                <label class="form__label form__component"> Phone Number</label>
                <input type="text" id="id_phone" maxlength="15" name="phone" class="form__input form__component js-form-input" required patter ="[[0-9]+"  minlength="9" />
                <span class="error">A valid phone number is required</span>         
              </div><!-- /form group -->
    
              <div class="form__group">

                <label for="id_adress" class="form__label form__component">Address </label>
                <input type="text"  id="id_adress" maxlength="200" name="adress"  class="form__input form__component js-form-input" required pattern="^[A-Za-z0-9 _]*[A-Za-z0-9][A-Za-z0-9 _]*$"  minlength ="6"  />
                <span class="error">A valid email is required</span>         
              </div>

              <div id ="contact_submit">
 
            <button type="submit" class="form__button button__submit button__add-order "  >Send
            </button>
      
              </div>
            </form>
          </article>
        </div>
      </section>
    </main><!-- /page content -->
  </div>

{% endblock %}

restaurant/templates/Order/orderStatus.html
{% extends 'base.html' %}

{% block content %}



  <h1> The menu selected </h1>
    <main class="page-content">
      <section class="page page-register wrapper default__gradient ">
        <div class="content">
          <div class = "wrapper__table wrapper__menu">
    
            <table class ="tableone table__check__status">
              <thead>
                <tr>
                  <th>Fel 1</th>
                  <th>Fel 2</th> 
                  <th>Fel 3</th>
                  <th>Starea comenzii</th>
                </tr>
              </thead>

            
              <tbody>
                <tr>
                  <td>{{m.fel1}}</td>
                  <td>{{m.fel2}}</td>
                  <td>{{m.desert}}</td>

                    {% ifequal 0 c.status %}  

                  <td> Pending </td> 
                      
                    {%endifequal%} 

                    {% ifequal 1 c.status %} 

                  <td> Sent </td> 

                    {%endifequal%} 

                    {% ifequal 2 c.status %} 

                  <td> Sent </td> 

                    {%endifequal%} 
                </tr>
        	
              </tbody>
            </table>

          </div>

        </div>
      </section>
    </main><!-- /page content -->
  

{% endblock %}

restaurant/templates/Order/verifyCode.html
{% extends 'base.html' %}

{% block content %}

  <div class = "content--menu">
    <main class="page-content">
      <section class="page page-register gradient__ciorba">
         <div class="content">

            <article class="card card__verify">
              <form class="form" action="" method="post">

                {% csrf_token %}

                  <div class="form__group">

   			            <input class="form__input form__component form__input__check
                    form__verify__input" placeholder="Enter Code" id="id_code" maxlength="100" name="code" type="text">
                    
                    <button type="submit"   class="form__button form__button__verify" >Verifica</button>
                     
                  </div>
   
    
    
              </form>
      
            </article>
    
      </section>
    
    </main>

  </div>

{% endblock content%}