Meniu/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    #   /menu/  urls
    #url for adding a menu, web form
    url(r'^$', views.get_name, name='get_name'),
    #url to display all the menus
    url(r'^view-menu/$', views.view_menu , name='view-menu'),
    #url to display the "today" menus
    url(r'^view-daily/$', views.view_daily_menus , name='view-daily'),
    #url to display the orders for a specified menu
    url(r'^(?P<pk>[0-9]+)/$', views.getOrders, name='orders_by_menu'),

    
    #url(r'^menus/(?P<pk>[0-9]+)/$', views.MenuDetail.as_view()),
]	

Order/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
	#   /order/  urls
	#url for adding an order, web form, after choosing the menu
    url(r'^new/(?P<pk>[0-9]+)/$', views.get_order, name='get_order'),
    #url to the form where you see the orders associated with a menu
    url(r'^(?P<pk>[0-9]+)/$', views.updateStatus, name='order_sent'),
    #url to the form where the order status is checked
    url(r'^check_code/$', views.get_code, name='check_code'),
    #url  for the page where is displayed the order details.
    url(r'^check_status/$', views.checkCode, name='check_status'),
]

api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #   /api/  urls
    #url for sending all the menus for today.
    url(r'^menus/$', views.MenuList.as_view()),
    #url for operations with a menu like update,delete 
    url(r'^menus/(?P<pk>[0-9]+)/$', views.MenuDetail.as_view()),
    #url to see all the orders(GET)/ to add a new order (POST)
    url(r'^orders/$', views.OrderList.as_view()),
    #url to check the details of an order
    url(r'^code/$', views.orderByCode.as_view()),
    #url to set the rating to an update
    url(r'^rating/$', views.updateRating.as_view()),
]	

restaurant/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import Meniu

urlpatterns = [
	url(r'^meniu/', include('Meniu.urls', namespace="meniu")),
	url(r'^order/', include('Order.urls', namespace="order")),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', Meniu.views.get_name),
]

Meniu/models.py
from __future__ import unicode_literals
from django.forms import ModelForm
from django.db import models

# Menu model
class Menu(models.Model):
    title = models.CharField(max_length = 200)
    datta = models.DateField('date published')
    fel1 = models.CharField(max_length = 200)
    fel2 = models.CharField(max_length = 200)
    desert = models.CharField(max_length = 200)

    def __unicode__(self):
        return self.title

Meniu/forms.py
import datetime 
from django import forms
from django.forms import ModelForm
from restaurant.utils import validateString
from Meniu.models import Menu

#class for the add menu form
class MenuForm(ModelForm):
    class Meta:
        model = Menu
        fields = ['title', 'datta', 'fel1', 'fel2', 'desert']

    def __init__(self, *args, **kwargs):
        super(MenuForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True
     
     #functions which ensure  that the input data is si valid, for the add menu form
    def clean(self):
        cleaned_data = super(MenuForm, self).clean()
        datta = cleaned_data.get('datta')
        title = cleaned_data.get('title')
        fel1 = cleaned_data.get('fel1')
        fel2 = cleaned_data.get('fel2')
        desert = cleaned_data.get('desert')

    def clean_datta(self):
        datta = self.cleaned_data.get('datta')
        today = datetime.date.today()
        if datta>=today:
            return datta
        raise forms.ValidationError("invalid date")

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if validateString(title) == True:
            return title
        raise forms.ValidationError("invalid date")

    def clean_fel1(self):
        fel1 = self.cleaned_data.get('fel1')
        if validateString(fel1) == True:
            return fel1
        raise forms.ValidationError("invalid date")

    def clean_fel2(self):
        fel2 = self.cleaned_data.get('fel2')
        if validateString(fel2) == True:
            return fel2
        raise forms.ValidationError("invalid date")

    def clean_desert(self):
        desert = self.cleaned_data.get('desert')
        if validateString(desert) == True:
            return desert
        raise forms.ValidationError("invalid date")




   

Meniu/views.py
from django.shortcuts import render,redirect
from django.template import loader
from Meniu.models import Menu
from Order.models import Order
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .forms import MenuForm
from django.contrib import messages
import datetime 



# method used to add a menu
def get_name(request):  
    if request.method == 'POST':
        # create a Menu form instance and populate it with data from the request:
        form = MenuForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            
            #saving the created object 
            form.save()
            #saves a message
            messages.success(request, 'Element added.')
            # redirect to a new URL:
            return redirect('meniu:view-menu')  
        else:
            messages.error(request, 'Data is invalid.')
    # if a GET (or any other method) we'll create a blank form
    else:

        form = MenuForm()
    #
    return render(request, 'Meniu/newMenu.html', {'form': form})

# method used to return all the avaible menus
def view_menu(request):
    menus = Menu.objects.all().order_by('datta')
    return render(request, 'Meniu/availableMenus.html', {'menu': menus})

# method used to return the avaible menus for today 
def view_daily_menus(request):
    today = datetime.date.today()
    menus = Menu.objects.all().filter(datta = today) 
    return render(request, 'Meniu/dailyMenus.html', {'menu': menus})

# method used to return the menu and the average raiting, orders for it.
def getOrders(request,pk):
    orders = Order.objects.filter(id_menu__pk=pk)
    meniu = Menu.objects.get(pk=pk)
    nrOrders = len(orders)
    if nrOrders>0:
        sumRating=0
        for i in  orders:
            sumRating += i.rating
        averageRating = sumRating/nrOrders
    else:
        averageRating=0
    return render(request, 'Meniu/ordersByMenu.html', {'n':meniu ,'o':averageRating, 'orders': orders})

restaurant/templates/Meniu/availableMenus.html
{% extends 'base.html' %}

{% block title %}People@ assist - Menus{% endblock %}

{% block para %}
    <p> People@ assist - Menus </p>
{% endblock para%}

{% block content %}

  <main class="page-content">
    <section class="page page-register wrapper gradient__ciorba ">
      <div class="content">
        <div class = "wrapper__table wrapper__menu">
          <table class ="table__view">
              <thead>
                <tr>
                  <th>Data</th>
                  <th>Titlu</th> 
                  <th>Actiuni</th>
                </tr>
              </thead>

                {%for m in menu %}
       
           
                <tr>
                  <td>{{m.datta}}</td>
                  <td>{{m.title}}</td> 
                  <td><a class ="button--state-success form__button form__order__button link--style" href = "{% url 'meniu:orders_by_menu' m.pk %}" > Vizualizare </a> </td>
                </tr>     

                {%endfor%}
    
          </table>
        </div>
      </div>
    </section>
  </main>

{% endblock %}


 

restaurant/templates/Meniu/dailyMenus.html
{% extends 'base.html' %}

{% block title %}People@ assist - Daily Menus{% endblock %}

{% block para %}
    <p> People@ assist -Daily Menus </p>
{% endblock para%}

{% block content %}
    
  <main class="page-content">  
    <section class="page page-register wrapper default__gradient ">
      <div class="content">
        <div class = "wrapper__table wrapper__menu">
          <table class ="table__view">
      
            <thead>
              <tr>
                <th>Titlu</th>
                <th>Fel 1</th>
                <th>Fel 2</th>
                <th>Desert</th>
                <th>Comanda</th>
              </tr>
            </thead>

          {%for m in menu %}
       
            <tbody>
              <tr>
                <td>{{m.title}}</td>
                <td>{{m.fel1}}</td>
                <td>{{m.fel2}}</td>
                <td>{{m.desert}}</td>
                <td> <a class="comanda__href" href="{% url 'order:get_order' m.pk %}" > Comanda </a> </td>
              </tr>
            </tbody>

          {%endfor%}

        </table>
      </div>
    </div>
  </section>
</main>
</div>
 

{% endblock %}

restaurant/templates/Meniu/newMenu.html
{% extends 'base.html' %}
{% load staticfiles %}
{%for message in messages %}
    {{ message }}
{% endfor %}

{% block content %}


<div class = "content-base">
  <main class="page-content">
    <section class="gradient--addmenu">
      <div class="content">

        <article class="card">
          <form class="form" action="" method="post">

            {% csrf_token %}

              <div class="form__group form__group__two ">
                <input type="text" id="id_title" maxlength="200" name="title"  class="form__input form__component form__inputformtwo " placeholder="Titlu">
                     
              </div>
    
              <div class="form__group form__group__two">
                <input type="text" id="id_datta" name="datta" class="form__input form__component form__inputformtwo" placeholder="Data">

              </div>
 
              <div class="form__group form__group__two ">
                <input type="text" id="id_fel1" maxlength="200" name="fel1"  class="form__input form__component form__inputformtwo" placeholder="Felul I">

              </div>

              <div class="form__group">
                <input type="text" id="id_fel2" maxlength="200" name="fel2" class="form__input form__component  form__inputformtwo" placeholder="Felul II">
            
              </div>

              <div class="form__group form__group__two">
                <input type="text" id="id_desert" maxlength="200" name="desert"  class="form__input form__component form__inputformtwo" placeholder="Felul III">
              
              <button type="submit" class="form__button--color  form__button  ">Send</button>

              </div>
    
    
          </form>
      
        </article>

      </div>
      
    </section>
    
  </main>

</div>

  {% endblock content%}



 
   
   

restaurant/templates/Meniu/ordersByMenu.html
{% extends 'base.html' %}

{% block title %}People@ assist - Menus{% endblock %}
{% block para %}
    <p> People@ assist - Menus </p>
{% endblock %}



{% block content %}

  <h1> The menu selected </h1>
    <main class="page-content">
      <section class="page page-register wrapper gradient__ciorba ">
        <div class="content">
          <div class ="container__table">
            <div class = "wrapper__table">
    
              <table class ="tableone">
         
                <thead>
                  <tr>
                    <th>Fel</th>
                    <th>Fel2</th> 
                    <th>Desert</th>
                    <th>Rating</th>
                  </tr>
                </thead>

            
                <tbody>
                  <tr>
                    <td>{{n.fel1}}</td>
                    <td>{{n.fel2}}</td>
                    <td>{{n.desert}}</td>         
                    <td> {{o}} </td>
                  </tr>
        
                </tbody>

              </table>
            </div>
        </div>
      <div class ="container__table">
        <div class = "wrapper__table">
            <table class="tabletwo" >
              <thead>
                <tr>
                  <th>Nume</th>
                  <th>Adress</th>
                  <th>Phone</th>
                  <th>Email</th>
                  <th>Rating</th>
                  <th>Status</th>
      
                </tr>
              </thead>

              <tbody>

                {%for m in orders %}

                  <tr>
                    <td>{{m.name}}</td>
                    <td>{{m.adress}}</td> 
                    <td>{{m.phone}}</td> 
                    <td>{{m.email}}</td>  
                    <td>
                      <span class="js-rating" data-rating="{{m.rating}}"></span>

                      <span class="star"></span>
                      <span class="star"></span>
                      <span class="star"></span>
                      <span class="star"></span>
                      <span class="star"></span>
                    </td>


                      {%ifequal 0 m.status%}  

                    <td> <a href = "{% url 'order:order_sent' m.pk %}" > Send</a> </td> 
                      {%endifequal%} 

                        {% ifequal 1 m.status %}  
                    <td>  Sent </td> 

                        {%endifequal%} 

                        {% ifequal 2 m.status %}  
                    <td> Sent</td> 

                        {%endifequal%} 
                  </tr>
          
                        {%endfor%}
              </tbody>
            </table>
          </div>
        </div>
      </section>
    </main>
  </div> 
  

{% endblock %}