Meniu/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    #   /menu/  urls
    #url for adding a menu, web form
    url(r'^$', views.get_name, name='get_name'),
    #url to display all the menus
    url(r'^view-menu/$', views.view_menu , name='view-menu'),
    #url to display the "today" menus
    url(r'^view-daily/$', views.view_daily_menus , name='view-daily'),
    #url to display the orders for a specified menu
    url(r'^(?P<pk>[0-9]+)/$', views.getOrders, name='orders_by_menu'),

    
    #url(r'^menus/(?P<pk>[0-9]+)/$', views.MenuDetail.as_view()),
]	

Order/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
	#   /order/  urls
	#url for adding an order, web form, after choosing the menu
    url(r'^new/(?P<pk>[0-9]+)/$', views.get_order, name='get_order'),
    #url to the form where you see the orders associated with a menu
    url(r'^(?P<pk>[0-9]+)/$', views.updateStatus, name='order_sent'),
    #url to the form where the order status is checked
    url(r'^check_code/$', views.get_code, name='check_code'),
    #url  for the page where is displayed the order details.
    url(r'^check_status/$', views.checkCode, name='check_status'),
]

api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #   /api/  urls
    #url for sending all the menus for today.
    url(r'^menus/$', views.MenuList.as_view()),
    #url for operations with a menu like update,delete 
    url(r'^menus/(?P<pk>[0-9]+)/$', views.MenuDetail.as_view()),
    #url to see all the orders(GET)/ to add a new order (POST)
    url(r'^orders/$', views.OrderList.as_view()),
    #url to check the details of an order
    url(r'^code/$', views.orderByCode.as_view()),
    #url to set the rating to an update
    url(r'^rating/$', views.updateRating.as_view()),
]	

restaurant/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import Meniu

urlpatterns = [
	url(r'^meniu/', include('Meniu.urls', namespace="meniu")),
	url(r'^order/', include('Order.urls', namespace="order")),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', Meniu.views.get_name),
]

restaurant/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">  
  <title>People @ASSIST</title>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <script src="{% static 'dist/assets/js/app.js' %}"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>

  <link rel="stylesheet" href="{% static 'dist/assets/css/app.css' %}">
</head>

<body>
  <div class = "header">
    <div class ="alignment"> 

      <a class ="header__img-logo" href="{% url 'meniu:get_name'%}"></a>

      <div class="header__dropdown dropdown">
        <button class="dropdown__button"><div class="dropdown__menu"><p class="dropdown__menu-name" >Menus</p></div></button>
        <div class="dropdown__content">
         
          <a href="{% url 'meniu:get_name'%}" ">Add Menu</a>
          <a href="{% url 'meniu:view-menu'%}">View orders</a>
          <a href="{% url 'meniu:view-daily'%}">Add Order</a>
          <a href="{% url 'order:check_code'%}">Check order</a>
         
        </div>  
      </div>
    </div>

    <div class="header__user">
      <p class="header__welcome">Hello, David Alexandr</p>
        <div class="header__img-account">
        </div>
    </div>

  </div>


  
  <div class="content-base">
  {% block content %}
   {% endblock %}
  </div>       
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
</body>

<footer>
  <p class="footer__copyright">Copyright 2016. The Archers</p>
</footer>

</html>